language: python
sudo: required
rvm:
  - 2.2.0
before_install:
- pip install --upgrade pip
- pip install xml2rfc
install:
- deactivate
- rvm install 2.2.0
- rvm use 2.2.0
- ruby --version
- gem install rake
- gem install cddl
script: 
- xml2rfc draft-ietf-cose-msg.xml -o cose.xml --exp
- rake verify
- make ghpages
env:
  global:
  - secure: <insert encrypted GH_TOKEN=blah here>
  - secure: UxxrSOF4wfTh1Y6zkFUqfROIdOibTtWZ7qK6HY1CDdzwl2kpXaJZ0g0FMV7fSfJsrLRjbUv3jl7Ob2JSDtIsWNE1OlG0bb+IqwG4cSTU5avDFJeDwqFGRYCmoqdeEUzyXuwfzhwq+6iVmwONMXsZal6Ww3yegcENnOYX9x/GmKI=
before_deploy: make submit
deploy:
  provider: releases
  api-key:
    secure: <insert encrypted API key here>
  file:
  - $TRAVIS_TAG.txt
  - $TRAVIS_TAG.html
  - $TRAVIS_TAG.xml
  skip_cleanup: true
  on:
    branch: master
    tags: true
